#!/bin/bash
#-*- mode:sh -*-
SCRDIR=$(dirname $(readlink -ef $0))

################################################################
#### default options

bin=$SCRDIR/ff-super

################################################################
#### main

plan(){
    echo $(whoami)@$(hostname)
    $bin -i 3 $OPTIONS \
        -f problem.pddl -o domain.pddl
}

finalize (){
    grep "^\(step\)\?\s*[0-9]\+: \(.*\)" $log | cut -d: -f 2 | sed -e "s/^ \(.*\)/(\1)/g" > plan
    [[ $(cat plan | wc -l) -gt 0 ]] && cp plan $probdir/$probname.plan
}

negatively-proven (){
    grep "problem proven unsolvable" $log || \
        grep "No plan will solve it" $log
}

report-results (){
    local cost=$(cat plan | wc -l)
    [[ -e plan && $cost -gt 0 ]] && echo "Plan cost: " $cost
}

plan-found (){
    local cost=$(cat plan | wc -l)
    [[ -e plan && $cost -gt 0 ]]
}

################################################################

. $SCRDIR/common.sh
